### ISSUE TITLE
run on google colab

### ISSUE THREAD

**Issue by zohreh3906** [lukecq1231/nli#6]
hello!
I have python 2 and theano 0.8.2.
I want run project in google colab.
I encounter the following error:

Theano does not recognise this flag: CUDA_DIR
  warnings.warn('Theano does not recognise this flag: {0}'.format(key))

I set device=cuda0 , but I see the following error:
ERROR (theano.sandbox.gpuarray): pygpu was configured but could not be imported

now, I run the code below:

!wget -c https://repo.continuum.io/archive/Anaconda2-5.1.0-Linux-x86_64.sh
!chmod +x Anaconda2-5.1.0-Linux-x86_64.sh
!bash ./Anaconda2-5.1.0-Linux-x86_64.sh -b -f -p /usr/local
!conda install theano pygpu

but , I have the following error:
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
....

Please check the implementation of the project on Google colab. I want to run Kim and ESIM projects on Google colab, but both give the same errors.
please help me.

**Comment by lukecq1231** [comment]
Sorry, I can't help you about the problems on google colab. Maybe your problem is because of the bad support of theano 0.9 on google colab. However, I have no experience about that.
